### ISSUE TITLE
 Name or service not known

### ISSUE THREAD

**Issue by giulio93** [FSonline23/World-Athletics-data-collection#2]
Running the script, the code return "Name or service not known".
Is the API endpoint or API key changed?

**Comment by Kingyeung129** [comment]
Hi @giulio93, yes you will need to update the API keys. You can find them in your browser's developer console network tab at [world athletics website](https://worldathletics.org/athletes-home). Find a POST request called graphql. The AWS API endpoint and API keys will be in the header. Copy them and replace the endpoint and API keys in api.json. Hope this helps!
